#Тестовые данные

GET http://localhost:3123/api HTTP/1.1

###

#Фильмы

## Получить список фильмов

GET http://localhost:5000/films HTTP/1.1
Content-Type: application/json

###

## Создать новый фильм

POST http://localhost:5000/films HTTP/1.1
Content-Type: application/json

{
  "name": "Legend",
  "postDate": "2023-01-23",
  "userId": "63cf9089c72fba65b72e62e4",
  "description": "Identical twin gangsters Ronald and Reginald Kray terrorize London during the 1960s.",
  "genre": "Crime",
  "released": 2015,
  "previewVideoLink": "https://11.react.pages.academy/static/film/video/traffic.mp4",
  "videoLink": "https://11.react.pages.academy/static/film/video/bubbles.mp4",
  "starring": [
      "Tom Hardy",
      "Emily Browning",
      "Taron Egerton"
    ],
  "director": "Brian Helgeland",
  "runTime": 132,
  "posterImage": "https://11.react.pages.academy/static/film/poster/Legend.jpg",
  "backgroundImage": "https://11.react.pages.academy/static/film/background/legend.jpg",
  "backgroundColor": "#E1DAD7"
}

###

# Пользователи
## Регистрация пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Jack",
  "email": "torans@overlook.net",
  "avatarUrl": "torrance.png",
  "password": "shining"
}

###

## Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "123456"
}

###